import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const topics = [
  { id: 1, title: "HOME", href: "/" },
  { id: 2, title: "ENV Variables", href: "/environment" },
  { id: 3, title: "SEO", href: "/seo" },
  { id: 4, title: "Images", href: "/performance" },
  { id: 5, title: "Dashboard", href: "/dashboard" },
];

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="site-header">
          <nav className="nav">
            <div className="nav-links">
              {topics.map((topic) => (
                <Link key={topic.id} href={topic.href} className="nav-link">
                  {topic.title}
                </Link>
              ))}
            </div>
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
